# Generated by Django 4.0.4 on 2022-09-26 04:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alumni', '0003_usercert'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserCert',
        ),
    ]
