# Generated by Django 4.0.4 on 2022-09-30 03:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('alumni', '0007_rename_oppaplications_applications_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='applications',
            options={'verbose_name_plural': 'Applications'},
        ),
        migrations.AlterModelOptions(
            name='eventattendees',
            options={'verbose_name_plural': 'Event Attendees'},
        ),
        migrations.AlterModelOptions(
            name='opportunities',
            options={'verbose_name_plural': 'Opportunities'},
        ),
        migrations.AlterField(
            model_name='applications',
            name='OppAplications',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alumni.opportunities'),
        ),
    ]
