# Generated by Django 4.0.4 on 2022-06-07 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_otp'),
    ]

    operations = [
        migrations.AddField(
            model_name='otp',
            name='is_valid',
            field=models.BooleanField(default=False),
        ),
    ]
