# Generated by Django 4.0.4 on 2022-10-07 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_course_complete_end_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='course_complete_end',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='course_complete_start',
            field=models.DateField(blank=True, null=True),
        ),
    ]
