# Generated by Django 4.0.4 on 2022-09-03 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_otp_is_valid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='mobile',
            field=models.CharField(default='', max_length=10),
            preserve_default=False,
        ),
    ]
