# Generated by Django 4.0.4 on 2022-09-26 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_user_batch_alter_user_college_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='display_name',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='show_certificate',
            field=models.BooleanField(default=True),
        ),
    ]
